### ISSUE TITLE
High Sierra support ("out of date")

### ISSUE THREAD

**Issue by gohai** [duo-labs/EFIgy-GUI#1]
I just tried the initial release on a MBP 14,1 running 10.13.1, and got all three items listed as "out of date". I am guessing this because your backend does not yet handle 10.13, but perhaps a different message would be in order?

BTW: I'd be really curious if `MBP141.0167.B00` is the expected System ROM for this machine. Over at https://github.com/Dunedan/mbp-2016-linux/issues/25 we're trying to figure out why the Fedora Live-CD image works for some, and not for others, so your findings that users tend to run vastly different versions of the EFI firmware is potentially relevant to figuring out what's going on. Thanks!

**Comment by swrobel** [comment]
They added [High Sierra support](https://github.com/duo-labs/EFIgy/commit/798116c0b5bd827b04febbfd156f4b44ff673985) but maybe this app needs an update? Doesn't seem to be working for me either
<img width="365" alt="screen shot 2017-11-22 at 11 31 23 pm" src="https://user-images.githubusercontent.com/157270/33159037-74f0c11a-cfdd-11e7-8114-3c86b5a60203.png">

<img width="277" alt="screen shot 2017-11-22 at 11 31 28 pm" src="https://user-images.githubusercontent.com/157270/33159036-70562e42-cfdd-11e7-971f-0a0d6c8fa8a5.png">

**Comment by jwwalker** [comment]
It doesn't work right on Sierra either.  It says my EFI firmware and OS build are out of date, but the tool tips show identical values for "expected" and "actual".

**Comment by jwwalker** [comment]
I see the reason for the problem.  In the methods `checkFirmwareVersions`, `checkHighestBuild`, and `checkOSUpToDate`, they are comparing `NSString*` values using `==` instead of `isEqualToString:`.

**Comment by futureimperfect** [comment]
Hi @gohai, @swrobel, and @jwwalker.

Sorry for the delay! The bug was fixed [here](https://github.com/duo-labs/EFIgy-GUI/commit/d997b30d32841271968fd38c47f480ba9879ae12), but we haven't released a new build yet.

I will update this issue once the new build is ready, but for now if you're able to build in Xcode yourselves you should see the correct results.

Thanks!

**Comment by futureimperfect** [comment]
Hi @gohai, @swrobel, and @jwwalker,

I released a new build that fixes this issue. Let me know if you have any issues with it!

Thanks for reporting! 🥇 💯
