### ISSUE TITLE
EFIgy considers beta builds out of date. 

### ISSUE THREAD

**Issue by PokeCaptain** [duo-labs/EFIgy-GUI#2]
Example video is in the link.
Just reran using the build that came out today.
https://drive.google.com/file/d/1L2sZKmp5JUz4ROntdIQsVgxLee0ubAou/view?usp=sharing

**Comment by PokeCaptain** [comment]
Just realized, should be a simple fix. Just check if the Build Number represented in hex is greater than or equal to the expected value. If so, it passes.

**Comment by swrobel** [comment]
Well, now the app is failing with 10.3.3 which is the actual latest macOS. It doesn't seem to recognize that 10.3.3 > 10.3.2 so it tells me I'm "out of date." Guys, I really appreciate what you're trying to do here, but I fear that you've done such a slapshod job that this tool is potentially doing more harm than good.

**Comment by futureimperfect** [comment]
@PokeCaptain @swrobel Thanks for the feedback!

Currently EFIgy-GUI compares the local results to what is returned from the EFIgy API, so if the version(s) returned by the API don't match what we get locally then you'll see these issues. I'll have a chat with @MyNameIsMeerkat and @bruienne about the best way to solve this.

Thanks again!

**Comment by futureimperfect** [comment]
This should be resolved now, but feel free to reopen if not. Thanks!
