### ISSUE TITLE
Crash on macOS 10.14.1 (2018 MacBook Pro T2)

### ISSUE THREAD

**Issue by JayBrown** [duo-labs/EFIgy-GUI#4]
Crash report appended below. I suspect it might have something to do with the fact that EFI validation etc. on the 2018 MacBook Pro is done via the T2.

[EFIgy_2018-11-04-110207.txt](https://github.com/duo-labs/EFIgy-GUI/files/2545706/EFIgy_2018-11-04-110207.txt)

**Comment by futureimperfect** [comment]
Hi @JayBrown,

Sorry for the (extremely) delayed response.

Does the app crash immediately upon opening? Also, were you running it from the `~/Downloads` folder or `/Applications`?

Thanks!

**Comment by JayBrown** [comment]
I'm running it from `~/Applications/Utilities`, but that's a default macOS applications directory, like `/Developer/Applications` etc., so it shouldn't be the cause of the problem.

The same crash happens when I launch it from `/Applications`.

Crash happen immediately upon launch. (Same behavior on 10.14.3.)

**Comment by futureimperfect** [comment]
Hi @JayBrown,

This should be fixed now in `master`, but I haven't released a new build yet. I'll try to get to that this week.

Thanks!

**Comment by futureimperfect** [comment]
Hi @JayBrown,

I just released [a new build that should fix this](https://github.com/duo-labs/EFIgy-GUI/releases/tag/v1.0.3). Let us know if you're still having trouble. Thanks!

**Comment by JayBrown** [comment]
Works! Thank you.
