### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by alvarnell** [duo-labs/EFIgy-GUI#5]
Have you abandoned this software? Has not been updated with several new firmware updates in over a year now.

**Comment by alvarnell** [comment]
Glad to see that the client has been updated to 1.0.2 which includes Mojave Dark Mode fixes, but pretty much worthless without having a database update in over a year now. Doesn't even recognize Mojave as a legitimate macOS, let alone builds and EFI.

**Comment by futureimperfect** [comment]
Hey @alvarnell,

Thanks for the feedback, these are all valid points. EFIgy and EFIgy-GUI aren't abandoned, but to be honest we haven't been able to give them the care and attention they need recently. I'm working on getting the data set updated though, and I will let you know as soon as that happens.

**Comment by swrobel** [comment]
@futureimperfect any luck on that database update?

**Comment by futureimperfect** [comment]
Hi @alvarnell and @swrobel,

After an exceptionally long delay we've finally updated the API and client. Apple updated some things related to EFI updates in update packages, so some retooling on both the client and server was required. Let me know if you're still seeing issues, but otherwise I'm closing this for now.

**Comment by alvarnell** [comment]
Not sure I fully understand with regard to updating the client. There has not been a new release of either the EFI-GUI or command line client posted for users yet.

**Comment by jelockwood** [comment]
@futureimperfect 
The command line version i.e. EFIgyLite_cli.py is now working - including now with the -o flag. Here is a sample result.

	Your firmware version 194.0.0 is the expected one for a MacBookPro14,3 running build 18F132. Smile, today is a good day :-)

However the GUI tool i.e. this one when run on the exact same Mac obviously with the same EFI firmware and build of macOS returns the following result.

![Screenshot 2019-06-18 at 10 15 08](https://user-images.githubusercontent.com/4300786/59669414-12f89d00-91b2-11e9-9035-bba6da5194ab.png)

This suggests the GUI tool v1.0.2 contrary to your comment above https://github.com/duo-labs/EFIgy-GUI/issues/5#issuecomment-502239928 is not yet 'fixed'.

Oops! I see there is a 'commit' not yet committed. Perhaps that is what is needed. :)

**Comment by alvarnell** [comment]
Thats almost correct. It hasn't been released yet, but as mentioned elsewhere, this commit should fix it: https://github.com/duo-labs/EFIgy-GUI/commit/c1428a8c5e262077abbb0559da62f6328bf08ea8
