### ISSUE TITLE
Discrepancy between what's reported in GUI and CLI (MacBookPro11,3 w/ 10.14.5)

### ISSUE THREAD

**Issue by GetMyMacOn** [duo-labs/EFIgy-GUI#6]
EFIgy-GUI and EFIgy-CLI report different results.

GUI thinks my firmware is out-of-date, while CLI says SUCCESS

Example screenshot - https://imgur.com/a/8IGAPio

This was tested on two machines a MacBookPro11,3 and MacBookPro11,5 with the same results

**Comment by alvarnell** [comment]
The GUI hasn't been updated since February. You'll need to wait for a new release.

**Comment by futureimperfect** [comment]
Hi @GetMyMacOn and @alvarnell,

I just uploaded [a new build of EFIgy-GUI](https://github.com/duo-labs/EFIgy-GUI/releases/tag/v1.0.3). If you get a chance can you let me know if you're still having trouble? Thanks!

**Comment by GetMyMacOn** [comment]
It’s working on a 2018 MacBook Pro

Thanks

**Comment by alvarnell** [comment]
Working now on my iMac, although the database isn't up-to-date.

> 
> 
> 	EFI firmware version check:
> 		[!] ATTENTION - It looks like your EFI version (175.0.0) is NEWER than the latest production release that is in the dataset (IM183.0172.B00). This is most likely because you are now, or have in the past, installed a developer preview OS and as part of that you also had newer EFI firmware installed. The EFIgy API currently only has reliable data for production OS releases.
> 
> 	Highest build number check:
> 		[-] ATTENTION - You are NOT running the latest release build number of your OS version (10.14.6). Your build number is 18G87, the latest release build number is 18F132
> 
> 	Up-to-date OS check:
> 		[!] ATTENTION - It looks like you might be running a development OS build 10.14.6. The EFIgy API currently only has reliable data for production OS releases.


-Al-

On Aug 8, 2019, at 14:00, James Barclay <notifications@github.com> wrote:

Hi @GetMyMacOn <https://github.com/GetMyMacOn> and @alvarnell <https://github.com/alvarnell>,

I just uploaded a new build of EFIgy-GUI <https://github.com/duo-labs/EFIgy-GUI/releases/tag/v1.0.3>. If you get a chance can you let me know if you're still having trouble? Thanks!

**Comment by futureimperfect** [comment]
Great, thanks for checking! I'll close this for now, but will also work on getting the database updated soon.
